name: frontend-service

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    restart: unless-stopped
    networks:
      - msngr-network

networks:
  msngr-network:
    external: true
